= svg2ico
:favicon:
:source-highlighter: rouge
:icons: font
:description: svg2ico is a Java library for converting SVG images to ICO images.  It is free to download and use in your project.

svg2ico converts SVG images into ICO images. It is written in Java, and is available as an Ant task. It is open source, and free for you to use.

// suppress inspection "AsciiDocLinkResolve"
The latest version of svg2ico available for download is https://github.com/svg2ico/svg2ico/releases/download/{revnumber}/svg2ico-{revnumber}.jar[{revnumber}]. The link:javadoc[javadoc] is also available online.

The project is https://github.com/svg2ico/svg2ico[hosted on GitHub].

== Downloads

Argo is available under the https://www.apache.org/licenses/LICENSE-2.0[Apache 2 license]. It can be downloaded in four forms:

- as a Gradle plugin, from the https://plugins.gradle.org/plugin/com.gitlab.svg2ico[Gradle Plugin Portal] using

[source,kotlin,subs="+attributes"]
----
plugins {
    id("com.gitlab.svg2ico") version "{revnumber}"
}
----
- as a Maven dependency from https://central.sonatype.com/artifact/net.sourceforge.svg2ico/svg2ico[Maven Central], using

[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>net.sourceforge.svg2ico</groupId>
    <artifactId>svg2ico</artifactId>
    <version>{revnumber}</version>
</dependency>
----
- as a https://github.com/svg2ico/svg2ico/releases/download/{revnumber}/svg2ico-{revnumber}.jar[jar], to use as an Ant task or from the command line, with source code and shadowed dependencies included,
- or as the full source code including tests etc. using Git from link:https://github.com/svg2ico/svg2ico.git[].

https://central.sonatype.com/artifact/net.sourceforge.svg2ico/svg2ico/versions[Previous versions] are also available.

== Gradle Instructions

=== Add the plugin to your build

Either Kotlin:

[source,kotlin,subs="+attributes"]
----
plugins {
    id("com.gitlab.svg2ico") version "{revnumber}"
}
----

or Groovy:

[source,groovy,subs="+attributes"]
----
plugins {
    id 'com.gitlab.svg2ico' version '{revnumber}'
}
----

=== Add a task to make an ICO

Kotlin:

[source,kotlin]
----
tasks.register("ico", com.gitlab.svg2ico.Svg2IcoTask::class) {
    source {
        sourcePath = file("resources/favicon.svg")
    }
    destination = project.layout.buildDirectory.file("icons/favicon.ico")
}
----

Groovy:

[source,groovy]
----
task ico (type : Svg2IcoTask) {
    source {
        sourcePath = file('resources/favicon.svg')
    }
    destination = project.layout.buildDirectory.file('icons/favicon.ico')
}
----

=== Add a task to make a PNG

Kotlin:

[source,kotlin]
----
tasks.register("png", com.gitlab.svg2ico.Svg2PngTask::class) {
    source = file("resources/favicon.svg")
    width = 128
    height = 128
    destination = project.layout.buildDirectory.file("icons/favicon.png")
}
----

Groovy:

[source,groovy]
----
task png (type : Svg2PngTask) {
    source = file('resources/favicon.svg')
    width = 128
    height = 128
    destination = project.layout.buildDirectory.file('icons/favicon.png')
}
----

=== Stylesheets

Both tasks accept a `userStyleSheet` parameter to specify a stylesheet to apply to the SVG, for example:

[source,kotlin]
----
tasks.register("ico", com.gitlab.svg2ico.Svg2IcoTask::class) {
    source {
        sourcePath = file("resources/favicon.svg")
        userStyleSheet = file("resources/user.css")
    }
    destination = project.layout.buildDirectory.file("icons/favicon.ico")
}
----

=== Refinements to ICO output

An ICO file can contain images at multiple resolutions, allowing the client to pick the most appropriate resolution.  By default, the `svg2ico` task will produce an ICO containing 64 x 64, 48 x 48, 32 x 32, 24 x 24, and 16 x 16 pixel resolutions.

The task supports specifying a different set of resolutions if you want to reduce the file size, or if you know the ICO will be rendered at a particular resolution, for example.

It's also possible to specify different source SVGs for different resolutions, so you can use a detailed source SVG for high resolutions and a simplified one for low resolutions.

The following example makes an ICO with a 64 x 64 image from a detailed SVG, and a 32 x 32 image from a simplified SVG.

[source,kotlin]
----
tasks.register("ico", com.gitlab.svg2ico.Svg2IcoTask::class) {
    source {
        sourcePath = file("resources/detailed-favicon.svg")
        output { width = 64; height = 64 }
    }
    source {
        sourcePath = file("resources/simplified-favicon.svg")
        output { width = 32; height = 32 }
    }
    destination = project.layout.buildDirectory.file("icons/favicon.ico")
}
----


== Command Line Example

svg2ico can be used from the command line to convert `resources/favicon.svg` to an ICO like this:

[source,,subs="+attributes"]
----
./svg2ico-{revnumber}.jar -src resources/favicon.svg -dest favicon.ico -width 32 -height 32
----
Three additional optional arguments are supported. `-depth` specifies the colour depth in bits per pixel, e.g. `-depth 8` outputs eight bits per pixel. The `-compress` flag causes the output to be compressed ICO format. The `-userStylesheet` allows a user stylesheet file to use during rendering to be provided, for example `-userStylesheet ./my-style.css`.

== Ant Example

svg2ico can be used as an Ant task to convert `resources/favicon.svg` to an ICO like this:

[source,xml,subs="+attributes"]
----
<target name="Convert SVG to ICO">
    <taskdef name="svg2ico"
        classname="net.sourceforge.svg2ico.Svg2IcoTask"
        classpath="lib/build/svg2ico-{revnumber}.jar"
    />
    <svg2ico src="resources/favicon.svg"
        dest="resources/favicon.ico"
        width="32"
        height="32"
    />
</target>
----
where `lib/build/svg2ico-{revnumber}.jar` points to where the svg2ico jar can be found. As with the command line, three optional attributes are supported. `depth` specifies the colour depth in bits per pixel, e.g. `depth="8"` outputs eight bits per pixel. `compress` causes the output to be compressed ICO, e.g. `compressed="true"`. `userStylesheet` specifies a user stylesheet to use for rendering, e.g. `userStylesheet="resources/favicon.css"`.

== Credits
svg2ico uses the excellent https://xmlgraphics.apache.org/batik/[Batik] and https://image4j.sourceforge.net/[image4j].